### ISSUE TITLE
add support to run streams in a subprocess

### ISSUE THREAD

**Issue by oliver-zehentleitner** [LUCIT-Systems-and-Development/unicorn-binance-websocket-api#126]
**Is your feature request related to a problem? Please describe.**
This lib is using multi-threading which is not really parallel in python - through the GIL all threads are executed sequential in a cycle. 

**Describe the solution you'd like**
wrap streams into processes instead of threads to bypass GIL

**Comment by kimchirichie** [comment]
if the streams become subprocesses, would that not hinder the main process ability to terminate the stream? how would you kill the stream?

**Comment by oliver-zehentleitner** [comment]
I need to test it out, I have no experience with that, but I have read some articles and when creating a new process, i think you can get the PID as result and it should be easy to kill/stop a process. And the processes can have a pipe to each other with `multiprocessing.Queue()`.

https://www.cloudcity.io/blog/2019/02/27/things-i-wish-they-told-me-about-multiprocessing-in-python/

**Comment by kimchirichie** [comment]
interesting. i wonder if benefits of multiprocessing is significant enough. i think parallel processing is mostly useful for computational scripts. in our case, its I/O network.

**Comment by oliver-zehentleitner** [comment]
if you do it not parallelo with multiprocessing than you are limited to one cpu core! even with 8 cores, your script can use only 12,5% of the cpu power of the system.

**Comment by kimchirichie** [comment]
youre 100% right. but does it need more than 1 core? its network I/O and most of the time, the process is not working. threading may be sufficient. (unless theres hundreds of connections)

**Comment by oliver-zehentleitner** [comment]
Try [this](https://github.com/oliver-zehentleitner/unicorn-binance-websocket-api/blob/master/example_stream_everything.py) and its just throwing away the receives.... not saving it to database or something else...

I think async.io is very cpu intensive.

**Comment by oliver-zehentleitner** [comment]
But you are right, its more a theoretical problem, 99,99% of all users will be not affected. Its very uncommon to stream **everything**, this does not make sense excepted for testing this lib :) - but if I find have the time, I think I will try it.

**Comment by kosmodromov** [comment]
Actually it makes sense because sometimes in periods of high volatility, network traffic increases significantly along with cpu that also needs for app logic. In case of streaming multiple timeframes on binance futures, for instance.

**Comment by CharlyEmpereurmot** [comment]
Indeed it would be great to be able to choose between Threads or Processes when starting to stream whatever.

In the meanwhile, for going around this and using Processes, maybe something in this spirit would work ?

```
#!/usr/bin/env python3

from multiprocessing import Process, Manager
import unicorn_binance_websocket_api
from datetime import datetime
import pytz
import time
import json


def handle_stream(bwsam, data, streams_uuids):

    while True:

        if bwsam.is_manager_stopping():
            exit(0)
        stream_payload = bwsam.pop_stream_data_from_stream_buffer()
        stream_signal = bwsam.pop_stream_signal_from_stream_signal_buffer()

        # process signal from websocket
        if stream_signal is not False:
            pair, period = streams_uuids[stream_signal['stream_id']]

            if stream_signal['type'] == 'CONNECT':
                if not data[pair]['stream_connected']:
                    data[pair]['stream_connected'] = True
                    print(f"{pair.upper()}_{period} -- {datetime.now(tz=pytz.utc).timestamp()} -- WARNING: Stream connected")

            elif stream_signal['type'] == 'DISCONNECT':
                if data[pair]['stream_connected']:
                    data[pair]['stream_connected'] = False
                    print(f"{pair.upper()}_{period} -- {datetime.now(tz=pytz.utc).timestamp()} -- WARNING: Stream disconnected")

        # process payload from websocket
        if stream_payload is False:
            time.sleep(0.1)
        else:
            stream_payload = json.loads(stream_payload)
            if 'stream' not in stream_payload:
                continue
            pair, datatype = stream_payload['stream'].split('@')
            period = datatype.split('_')[-1]

            # stream data
            open_ts = stream_payload['data']['k']['t']
            close_price = stream_payload['data']['k']['c']

            print(f"{pair.upper()}_{period} -- {datetime.now(tz=pytz.utc).timestamp()} @ {open_ts} -- Price: {close_price}")


if __name__ == "__main__":

    mp_manager = Manager()
    data = mp_manager.dict()
    streams_uuids = mp_manager.dict()

    bwsam_1 = unicorn_binance_websocket_api.BinanceWebSocketApiManager(exchange="binance.com", enable_stream_signal_buffer=True)
    stream_uuid = bwsam_1.create_stream(channels=['kline_1m'], markets=['BTCUSDT'])
    data['BTCUSDT'] = {
        'period': '1m',
        'stream_connected': False,
        'stream_uuid': stream_uuid
    }
    streams_uuids[stream_uuid] = 'BTCUSDT', '1m'

    bwsam_2 = unicorn_binance_websocket_api.BinanceWebSocketApiManager(exchange="binance.com", enable_stream_signal_buffer=True)
    stream_uuid = bwsam_2.create_stream(channels=['kline_1m'], markets=['ETHUSDT'])
    data['ETHUSDT'] = {
        'period': '1m',
        'stream_connected': False,
        'stream_uuid': stream_uuid
    }
    streams_uuids[stream_uuid] = 'ETHUSDT', '1m'

    p1 = Process(target=handle_stream, args=(bwsam_1, data, streams_uuids, ))
    p2 = Process(target=handle_stream, args=(bwsam_2, data, streams_uuids, ))
    p1.start()
    p2.start()
    print('Processes start') 
```

**Comment by oliver-zehentleitner** [comment]
The problem with subproccesses (and in your script) is that no memory objects can be shared. 

Example:
you start a script (Process 1) and in this process you initiate an object. 
then you create a new process (Process 2) and pass the initiated object - this object will be copied and is not a reference. Process 1 and 2 use different objects!
I just wanted to prove this by a source and found this: https://docs.python.org/3/library/multiprocessing.shared_memory.html
Apparently this is new since Python 3.8: https://mingze-gao.com/posts/python-shared-memory-in-multiprocessing/

I'm in a bit of a hurry right now and I'm not quite sure if this is really a solution, but I think this is the direction it should go.

**Comment by oliver-zehentleitner** [comment]
No longer fits directly into the concept - we work with AsyncIO and Kubernetes and no longer need sub-processes.

If someone really urgently needs it, please contact us: https://www.lucit.tech/get-support.html
