### ISSUE TITLE
How to trap `Exception ConnectionClosed` errors?

### ISSUE THREAD

**Issue by OneArb** [LUCIT-Systems-and-Development/unicorn-binance-websocket-api#211]
Could you please provide some guidance on how to recover from

`CRITICAL:root:BinanceWebSocketApiSocket.start_socket(6803db6a-2255-4e73-9132-0bb8d38633ff, ['trade'], ['fttusdt']) - Exception ConnectionClosed - error_msg: sent 1011 (unexpected error) keepalive ping timeout; no close frame received`

I am using a two physical core laptop, python 3.9, unicorn 1.34.2, trading on two exchanges, streaming some web charts and I get after some time:

`WARNING:root:BinanceWebSocketApiManager._frequent_checks() - High CPU usage since 5 seconds: 100.0`

Until I upgrade, I'd like to attempt recovering critical streams. I monitor price levels, lost data is acceptable.

I have added

`logging.basicConfig(level=logging.INFO,
                    filename=os.path.basename(__file__) + '.log',
                    format="{asctime} [{levelname:8}] {process} {thread} {module}: {message}",
                    style="{")`
                    
before

`binance_websocket_api_manager = BinanceWebSocketApiManager(exchange='binance.com',
                                                               output_default='UnicornFy')`
                                                               
but I do not see any log file.

How do I trap `Exception ConnectionClosed` errors so I can attempt a `set_restart_request(stream_id)`?

Is it worth the effort since the lib already attempted the recovery?

Some streams, usually the ones receiving the most packets stay alive, which leads me to think I could resume or start a (new) stream.

I try to minimize processing: 

- after reading first quote:
`binance_websocket_api_manager.clear_stream_buffer(stream_buffer_name=stream_id)`

- and initialize with:
`number_of_max_entries = 0`
` binance_websocket_api_manager.set_keep_max_received_last_second_entries(number_of_max_entries)`

**Comment by oliver-zehentleitner** [comment]
The philosophy of this library is that it takes care of reconnects itself.

It would help me a lot if you post your logfile and python version. 

You are using the stream_buffer right?

How many entries of this kind do you have?
`WARNING:root:BinanceWebSocketApiManager._frequent_checks() - High CPU usage since 5 seconds: 100.0`

Important to understand is that Python uses only about the power of one CPU core, no matter how many cores you have! 

If your script/program constantly gets too little system performance, the backlog of incoming websocket data will grow and eventually the websocket connection will be terminated.

Translated with www.DeepL.com/Translator (free version)

**Comment by OneArb** [comment]
Please review the [two new log files](https://github.com/OneArb/-unicorn-binance).

**Comment by oliver-zehentleitner** [comment]
I am able to reconstruct `sent 1011 (unexpected error) keepalive ping timeout; no close frame received` and will release a fix soon.

**Comment by oliver-zehentleitner** [comment]
Interesting!

`stream_buffer_maxlen = 0` makes no sense!

its the max length of the stream_ buffer... if set to 3 the stack will not store more than 3 items in the buffer...

Yeah, it should  become part of coding club but isnt done yet!

What channel type do you use to get the last price?

**Comment by OneArb** [comment]
> stream_buffer_maxlen = 0 makes no sense!

I was also surprised that setting let, not only one quote but several quotes through, using either `trade` or `aggTrade`

```
                event_time = sl.get('event_time')
                
                # test code - quote per block
                if event_time == event_time_previous:
                        same_time += 1
                        symb = sl.get('symbol')
                        print(symb ,'multiple time', same_time)

                # process last quote only
                if event_time > event_time_previous:

                    same_time = 0  # test code - quote per block
                    event_time_previous = event_time
```
I was tabulating the number of quote received per packet, for a single symbol per stream, expecting the stream to stop - it did not.

On a side note, issuing `binance_websocket_api_manager.clear_stream_buffer()` right after the first quote is read, also lets several quotes per stream go through as well.

Does clearing the stream buffer happen through another thread which introduces some lag in the clearing?

**Comment by OneArb** [comment]
> I am able to reconstruct sent 1011 (unexpected error) keepalive ping timeout; no close frame received and will release a fix soon.

I am looking forwards to testing the fix!

**Comment by 45by90** [comment]
Hello,

Strangely, I've used this EXCELLENT library for over a month now, and just today this started happened.  I think, although not sure, that recently I updated my pip/python.

Best,

John

**Comment by OneArb** [comment]
> updated my pip/python

From which version?

**Comment by oliver-zehentleitner** [comment]
I analyzed the logfiles and only the b version is cointaining this 1011 error:
```
oliver@prestige:~/Downloads$ cat NGFQ014-03-b-exception-3.py.log | grep " 1011 "
2021-10-22 00:26:17,413 [DEBUG   ] 1492658 140488036312640 protocol: > CLOSE 1011 (unexpected error) keepalive ping timeout [24 bytes]
2021-10-22 00:26:22,978 [DEBUG   ] 1492658 140488539612736 protocol: > CLOSE 1011 (unexpected error) keepalive ping timeout [24 bytes]
2021-10-22 00:26:24,705 [DEBUG   ] 1492658 140488815715904 protocol: > CLOSE 1011 (unexpected error) keepalive ping timeout [24 bytes]
2021-10-22 00:26:37,436 [CRITICAL] 1492658 140488036312640 unicorn_binance_websocket_api_socket: BinanceWebSocketApiSocket.start_socket(f4518fa7-2aa2-4b85-acbe-371261371135, ['trade'], ['btcusdt']) - Exception ConnectionClosed - error_msg: sent 1011 (unexpected error) keepalive ping timeout; no close frame received
2021-10-22 00:26:43,003 [CRITICAL] 1492658 140488539612736 unicorn_binance_websocket_api_socket: BinanceWebSocketApiSocket.start_socket(9002225d-21ce-4ee5-acdc-984d992f334e, ['trade'], ['bnbusdt']) - Exception ConnectionClosed - error_msg: sent 1011 (unexpected error) keepalive ping timeout; no close frame received
2021-10-22 00:26:44,724 [CRITICAL] 1492658 140488815715904 unicorn_binance_websocket_api_socket: BinanceWebSocketApiSocket.start_socket(504d21bd-b372-4d79-b640-615df547406e, ['trade'], ['dogeusdt']) - Exception ConnectionClosed - error_msg: sent 1011 (unexpected error) keepalive ping timeout; no close frame received
```

As you can see, they all happend at the same time on 3 different streams... and they all recoverd!!

**Comment by oliver-zehentleitner** [comment]
If someone experience this without a restart please open a new issue with detailed information, thanks
