### ISSUE TITLE
binance.com-futures: no data received after stream restart 

### ISSUE THREAD

**Issue by jakaGH** [LUCIT-Systems-and-Development/unicorn-binance-websocket-api#216]
**First of all, thanks for a great package, it saves a ton of work.**

I observe some unusual behavior and I am unable to resolve it on my own. In short, I am using the websocket manager to receive the data from binance futures (BinanceWebSocketApiManager(exchange="binance.com-futures")) for 128 markets and 11 channels (klines only). After some time the data stops streaming on some channels while other channels seem unaffected. 

**BRIEF CODE DESCRIPTON**
The code is built on top of one of the examples with minor modifications. On kline close, I generate a file and write the kline data into it (very similar to print_stream_data_from_stream_buffer from example), and then in a separate thread, I process (add to the database) the data from the generated files.

**INTERNET CONNECTION AND HARDWARE**
There are some instances when CPU usage was high (95-99.3%) but this didn't happen when the problem with lost data arose. Otherwise, the app is run on a decent hosting package (10 cores, 16GB RAM).

**LONGER DESCRIPTION OF THE PROBLEM**
I attached both the log and the console output of the problem. From the console output, it is evident that something happened between 2021-11-13 10:12:07 (line 7975 in console and line 2050 in logfile) and 2021-11-13 10:23:02 (line 8453 in console) where multiple exceptions were raised. All are of the same sort:

> Exception in thread Thread-270:
> Traceback (most recent call last):
>   File "/opt/alt/python37/lib64/python3.7/threading.py", line 926, in _bootstrap_inner
>     self.run()
>   File "/opt/alt/python37/lib64/python3.7/threading.py", line 870, in run
>     self._target(*self._args, **self._kwargs)
>   File "/venv/3.7/lib/python3.7/site-packages/unicorn_binance_websocket_api/unicorn_binance_websocket_api_manager.py", line 473, in _create_stream_thread
>     loop.run_until_complete(socket.start_socket())
>   File "/opt/alt/python37/lib64/python3.7/asyncio/base_events.py", line 587, in run_until_complete
>     return future.result()
>   File "/venv/3.7/lib/python3.7/site-packages/unicorn_binance_websocket_api/unicorn_binance_websocket_api_socket.py", line 68, in start_socket
>     symbols=self.symbols) as websocket:
>   File "/venv/3.7/lib/python3.7/site-packages/unicorn_binance_webso
[logfile.log](https://github.com/oliver-zehentleitner/unicorn-binance-websocket-api/files/7533397/logfile.log)
cket_api/unicorn_binance_websocket_api_connection.py", line 147, in __aenter__
>     self.manager.websocket_list[self.stream_id] = await self._conn.__aenter__()
>   File "/venv/3.7/lib/python3.7/site-packages/websockets/legacy/client.py", line 632, in __aenter__
>     return await self
>   File "/venv/3.7/lib/python3.7/site-packages/websockets/legacy/client.py", line 649, in __await_impl_timeout__
>     return await asyncio.wait_for(self.__await_impl__(), self.open_timeout)
>   File "/opt/alt/python37/lib64/python3.7/asyncio/tasks.py", line 449, in wait_for
>     raise futures.TimeoutError()
> concurrent.futures._base.TimeoutError

There are also other instances where this type of exception was raised. However, those instances didn't interfere with the streams while after 2021-11-13 10:23:02 one of the streams (2cf648c7-3b08-4331-aaed-fc1acc7474c8; it was also restarted several times) doesn't receive any more data.

Do you have any suggestions on how to avoid this behavior? Am I using too many channels/markets at once perhaps? It is very difficult to reproduce the problem since the behavior occurred only after 21 hours of running the app...

Thanks in advance for any suggestions!
-Jaka
[logfile.log](https://github.com/oliver-zehentleitner/unicorn-binance-websocket-api/files/7533398/logfile.log)
[console.txt](https://github.com/oliver-zehentleitner/unicorn-binance-websocket-api/files/7533399/console.txt)

**Comment by djangoengine** [comment]
I have had similar issues, streaming stops after 24 hours or so.
The binance stops pushing data.
I tried restarting the sockets however it won't work.

**Comment by oliver-zehentleitner** [comment]
this seems to be a duplicate, go further here: https://github.com/LUCIT-Systems-and-Development/unicorn-binance-websocket-api/issues/221
