### ISSUE TITLE
Binance Futures Testnet URLs are wrong

### ISSUE THREAD

**Issue by Animouse31** [LUCIT-Systems-and-Development/unicorn-binance-websocket-api#239]
Hi Oliver!

Thank you for the wonderful module, I love it very much.

I want to report a bug for the Futures Testnet URLs.

It takes me some time to figure out the problem, even contacting Binance customer service. It turns out the URLs for Binance Futures Testnet in the manager.py are wrong.

Here's the code:

elif self.exchange == "binance.com-futures-testnet":
      # Todo: Needs a test
      self.API_URL = "https://testnet.binance.vision/api"
      self.MARGIN_API_URL = " https://api.binance.com/sapi"
      self.WEBSITE_URL = "https://testnet.binance.vision"
      self.FUTURES_URL = "https://fapi.binance.com/fapi"
      self.FUTURES_DATA_URL = "https://fapi.binance.com/futures/data"
      self.FUTURES_COIN_URL = "https://fapi.binance.com/fapi"
      self.FUTURES_COIN_DATA_URL = "https://dapi.binance.com/futures/data"

It uses Binance Spot Testnet URLs instead of Binance Futures Testnet URLs. For the Binance Futures Testnet URLs, it's supposed to be: "https://testnet.binancefuture.com/fapi"

testnet.binancefutures.com instead of testnet.binance.vision

As shown in the documentation: https://python-binance.readthedocs.io/en/latest/binance.html

![image](https://user-images.githubusercontent.com/81606382/155274096-df4b864c-2ad0-474e-b5ad-3716aeb5aca5.png)

**Comment by oliver-zehentleitner** [comment]
Why did you close it?
