### ISSUE TITLE
stream_is_crashing

### ISSUE THREAD

**Issue by rdvnszn1** [LUCIT-Systems-and-Development/unicorn-binance-websocket-api#246]
I want to connect about 50 pairs to get  depth5   channel    but I got  an error like that

I try many version of this library, but not solved, I try it in my local laptop  and a powerful azure server, not solved again, it worked with 5-10 pairs but can not connect more,  but I used it with that amount pair before (I have problems for 1-2 days)

BinanceWebSocketApiSocket.start_socket(d05116db44f2-fdc4-d94c-9c49-23745395, ['depth5'], ['xrpusdt', 'omgusdt', 'bandusdt', 'mkrusdt', 'avaxusdt', 'dotusdt', 'xtzusdt', 'atomusdt', 'trxusdt', 'reefusdt', 'hotusdt', 'wavesusdt', 'ontusdt', 'linkusdt', 'chzusdt', 'rvnusdt', 'batusdt', 'lrcusdt', 'ltcusdt', 'bchusdt', 'xlmusdt', 'dogeusdt', 'adausdt', 'neousdt', 'eosusdt', 'uniusdt', 'aaveusdt', 'balusdt', 'zilusdt', 'algousdt', 'enjusdt', 'thetausdt', 'ognusdt', 'grtusdt', 'maticusdt', 'crvusdt', 'manausdt', 'solusdt', 'vetusdt', 'ankrusdt', '1000shibusdt', 'icpusdt', 'ftmusdt', 'lptusdt', 'axsusdt', 'ensusdt', 'audiousdt', 'sandusdt', 'aliceusdt', 'tlmusdt', 'galausdt']) - Exception ConnectionClosed - error_msg: sent 1011 (unexpected error) keepalive ping timeout; no close frame received
BinanceWebSocketApiManager.stream_is_crashing(d05116db44f2-fdc4-d94c-9c49-23745395)

**Comment by oliver-zehentleitner** [comment]
Please provide the asked information!

Please read this: https://github.com/LUCIT-Systems-and-Development/unicorn-binance-websocket-api/issues/113

**Comment by oliver-zehentleitner** [comment]
This is maybe also interesting: https://github.com/LUCIT-Systems-and-Development/unicorn-binance-websocket-api/issues/126

**Comment by oliver-zehentleitner** [comment]
Maybe you are interested about a depth cache: https://github.com/LUCIT-Systems-and-Development/unicorn-binance-local-depth-cache

**Comment by oliver-zehentleitner** [comment]
If needed reopen a new issue with all the infos we need.
