### ISSUE TITLE
add the option to daemonize threads

### ISSUE THREAD

**Issue by MoeQatoum** [LUCIT-Systems-and-Development/unicorn-binance-websocket-api#264]
### Is your feature request related to a problem? Please describe.

why not add the option to daemonize threads , so they would be killed if main thread is closed. in my case if I close the main window of my app , the process is still alive due this issue , I think it would be easier and more convenient to just daemonize threads rather than closing them manually.

I looked in to the code it's a couple of lines modification.

thanks for your great work !

**Comment by oliver-zehentleitner** [comment]
hi! thanks for the suggestion.

I tried to fix some other issues, but fixing them caused this new behavior. threads and loops must be stopped clearly during runtime, not only when closing the application.

In a few weeks this will be fixed with a clean solution.
