### ISSUE TITLE
What does "Adding timeout to websocket.recv()" error mean?

### ISSUE THREAD

**Issue by am11y** [LUCIT-Systems-and-Development/unicorn-binance-websocket-api#277]
At the startup of script, I get errors:

Adding timeout to `websocket.recv()`  (connection.py:71)

![image](https://user-images.githubusercontent.com/63109448/171759769-23184eb8-4672-41ce-a2d2-010d29afa631.png)

**Comment by oliver-zehentleitner** [comment]
Its not an error, its a hint!

Ok, I see its defined as error, i will change that to info in the next release.

We had the problem, that we could not close websocket connections that does not receive data, like an idling userData stream: https://github.com/LUCIT-Systems-and-Development/unicorn-binance-websocket-api/blob/0dfeed666edda730e3cfb2726a50e87143a46ab1/unicorn_binance_websocket_api/connection.py#L285

```
# This is a dirty workaround and only a temporary solution
# using wait_for is slowing down the receiving by 50% under full load. But without userdata streams
# wont close without the awaited future
```

**Comment by dima-dmytruk23** [comment]
Up
