### ISSUE TITLE
Clean buffer

### ISSUE THREAD

**Issue by Rizhiy** [LUCIT-Systems-and-Development/unicorn-binance-websocket-api#293]
### Is your feature request related to a problem? Please describe.

Currently, stream buffers sometimes contain strange messages like:
```
{'id': 1, 'result': None, 'unicorn_fied': ['binance.com-futures', '0.12.2']}
```
This requires writing of extra code to check for such messages and discard them.

### Describe the solution you'd like.

Have a clean buffer/function to get clean buffer which only contain actual data.

### Describe alternatives you've considered

I'm currently cleaning the buffer in my own code, which is not ideal.

**Comment by oliver-zehentleitner** [comment]
This message means, that the subscriptions are confirmed.... 

if you are subscribing to just one channel (create_stream), the stream is subscribing via websocket URI. then there is no message like this.
if you subscribe to 2 or more channels, then the subscriptions are done via `websocket.send()` and then binance answers with this message to confirm the subscription... 
There are not only "result" messages, but also "error" messages.

Not sure if this is really needed, but if we implement this, we have to keep in mind, that the lib must not get blind on those kind of messages, for example ['get_stream_subscriptions()'](https://unicorn-binance-websocket-api.docs.lucit.tech/unicorn_binance_websocket_api.html?highlight=error#unicorn_binance_websocket_api.manager.BinanceWebSocketApiManager.get_stream_subscriptions) is triggering a result message and returns it... 

And. do we only hide result messages? I think its good if there is an error, that it gets delivered to the developer even if it crashes the algo for one time. then the dev is learning and getting aware of the reason behind it. anything else can lead to bigger problems.
