### ISSUE TITLE
Event: Balance and Position Update (Binance Futures)

### ISSUE THREAD

**Issue by esteban2006** [LUCIT-Systems-and-Development/unicorn-binance-websocket-api#298]
Hi there, 

More than an issue, this is just a question about a local feed 

How can I add, Event: Balance and Position stream? [binance link](https://binance-docs.github.io/apidocs/futures/en/#event-balance-and-position-update)

Using this [example_stream_everything.py](https://github.com/LUCIT-Systems-and-Development/unicorn-binance-websocket-api/blob/master/example_stream_everything.py)  file

Best Regards,

**Comment by oliver-zehentleitner** [comment]
thats a simple userData stream....

**Comment by esteban2006** [comment]
@oliver-zehentleitner could you address me  how?
