### ISSUE TITLE
Ease testing with own websocket server

### ISSUE THREAD

**Issue by dima-dmytruk23** [LUCIT-Systems-and-Development/unicorn-binance-websocket-api#304]
### Is your feature request related to a problem? Please describe.

I need to replace the exchange with my mock server so that I can test the client for a load. Since there is a lot of hardcode in the code and a lot of coupling - to do this without crutches, patching is very difficult and time consuming.
I propose to make the initialization of the manager in this regard - more flexible.

### Describe the solution you'd like.

To replace the exchange with your mock server, just specify `exchange=Exchanges.LOCALHOST, exchange_type='dex'` (or `cex`) when initializing the manager. `exchange_type` must be specified only for `Localhost`. You can also set `websocket_base_uri` and `max_subscriptions_per_stream` otherwise the default values ​​will be applied.

**Comment by oliver-zehentleitner** [comment]
Basically, this is support for TCP Redirect right? So socks5 proxies should become supported too?

**Comment by dima-dmytruk23** [comment]
> socks5 proxies

Didn't try - I didn't have such a task. But it is quite feasible.

**Comment by oliver-zehentleitner** [comment]
I merged the PR thank you, but i removed the LOCALHOST settings. This will be included in the  next relaease > 1.42.0

**Comment by oliver-zehentleitner** [comment]
https://github.com/LUCIT-Systems-and-Development/unicorn-binance-websocket-api/releases/tag/1.43.0
