### ISSUE TITLE
userData stream doesn't send any data after 1.45 update 

### ISSUE THREAD

**Issue by NeutK** [LUCIT-Systems-and-Development/unicorn-binance-websocket-api#326]
### Version of this library.

1.45.2

### Solution to Issue cannot be found in the documentation or other Issues and also occurs in the latest version of this library.

- [X] I checked the documentation and other Issues. I am using the latest version of this library.

### Hardware?

Local server/workstation

### Operating System?

Linux

### Python version?

Python3.8

### Processing method?

stream_buffer

### Used endpoint?

binance.com-futures

### Issue

I have not updated the lib since 1.42 release. After updating to 1.45, I cannot receive any data from my private userData websocket. 

```
from unicorn_binance_websocket_api.manager import BinanceWebSocketApiManager
import time
import threading

def print_stream_data_from_stream_buffer(binance_websocket_api_manager):
    while True:
        if binance_websocket_api_manager.is_manager_stopping():
            exit(0)
        oldest_stream_data_from_stream_buffer = binance_websocket_api_manager.pop_stream_data_from_stream_buffer()
        if oldest_stream_data_from_stream_buffer is False:
            time.sleep(0.01)
        else:
            print (oldest_stream_data_from_stream_buffer)

binance_websocket_api_manager = BinanceWebSocketApiManager(exchange="binance.com-futures")
binance_api_key = ""
binance_api_secret = ""
userdata_stream_id = binance_websocket_api_manager.create_stream(["arr"],
                                                                 ["!userData"],
                                                                 api_key=binance_api_key,
                                                                 api_secret=binance_api_secret)

worker_thread = threading.Thread(target=print_stream_data_from_stream_buffer, args=(binance_websocket_api_manager,))
worker_thread.start()
```

I used this test script on both my server and locally. Doesnt get any stream data. Btw, public streams work fine.  
After testing releases, the problem occurs when updating 1.43.3 to 1.44.0.

**Comment by NeutK** [comment]
[logfile.log](https://github.com/LUCIT-Systems-and-Development/unicorn-binance-websocket-api/files/11190776/logfile.log)

**Comment by oliver-zehentleitner** [comment]
This log file shows only ~30 seconds of the lifetime of this stream. Did you trigger some events on binance in the meantime? Sorry for asking stupid questions but i wasted a lot of time in the past with such things so i ask first :)

**Comment by NeutK** [comment]
Yes, I did. Here, How it is look like when I downgraded to 1.43.3
[logfile.log](https://github.com/LUCIT-Systems-and-Development/unicorn-binance-websocket-api/files/11190860/logfile.log)

**Comment by oliver-zehentleitner** [comment]
Ok thanks!

I need to test it myself, I think i can fix it till tomorrow. I post it here as soon its fixed.

**Comment by oliver-zehentleitner** [comment]
I am testing the next couple of hours, then i prepare a package...

**Comment by 3o45d** [comment]
[test.py.log](https://github.com/LUCIT-Systems-and-Development/unicorn-binance-websocket-api/files/11211692/test.py.log)
log-file

**Comment by oliver-zehentleitner** [comment]
Please update to 1.46.0: https://github.com/LUCIT-Systems-and-Development/unicorn-binance-websocket-api/releases/tag/1.46.0

Can you confirm that this bug is fixed?

**Comment by Tarryhao** [comment]
I just verified the 1.46.0 websocket, and I have been able to get the push of the future account. In addition, I would like to ask, how to cancel the monitoring output of the CPU?

**Comment by oliver-zehentleitner** [comment]
Thank you! Also in my tests everything worked fine. I close it. Feel free to ask here if there are still questions.

**Comment by oliver-zehentleitner** [comment]
> I just verified the 1.46.0 websocket, and I have been able to get the push of the future account. In addition, I would like to ask, how to cancel the monitoring output of the CPU?

[You mean this?](https://github.com/LUCIT-Systems-and-Development/unicorn-binance-websocket-api/issues/132)
