### ISSUE TITLE
Question: How to stop manager properly while encounter exceptions like KBInterrupt or others?

### ISSUE THREAD

**Issue by Hub-or** [LUCIT-Systems-and-Development/unicorn-binance-websocket-api#334]

**Comment by oliver-zehentleitner** [comment]
Hello!

Please read the readme, there you will find all relevant questions for a successful implementation linked.

An example for your question:
https://github.com/LUCIT-Systems-and-Development/unicorn-binance-websocket-api/blob/master/example_ctrl-c.py

Best regards,
Oliver
