### ISSUE TITLE
get_exchange_info does not work in websocket API - easy fix included

### ISSUE THREAD

**Issue by fpaincha** [LUCIT-Systems-and-Development/unicorn-binance-websocket-api#346]
### Version of this library.

1.46.1

### Solution to Issue cannot be found in the documentation or other Issues and also occurs in the latest version of this library.

- [X] I checked the documentation and other Issues. I am using the latest version of this library.

### Hardware?

Local server/workstation

### Operating System?

Windows

### Python version?

Python3.10

### Installed packages

```shell
Not relevant here.
```

### Logging output

```shell
Not relevant here.
```

### Processing method?

stream_buffer

### Used endpoint?

concerns all

### Issue

Congrats - this library is just marvellous!

The source code for method get_exchange_info in the websocket API reads as:

[snip]

        if symbol is None:
            params = {"symbol": symbol}
        if symbols is None:
            symbols = [symbol.upper() for symbol in symbols]
            params = {"symbols": symbols}
        if permissions is None:
            params = {"permissions": permissions}

[snip]

All of those three method parameters are None by default. Of course, what was meant was this instead:

        params = {}
        if symbol is not None:
            params = {"symbol": symbol}
        elif symbols is not None:
            symbols = [symbol.upper() for symbol in symbols]
            params = {"symbols": symbols}
        elif permissions is not None:
            params = {"permissions": permissions}

This fixes method get_exchange_info...

Cheers.

**Comment by oliver-zehentleitner** [comment]
thank you! is fixed now!

**Comment by oliver-zehentleitner** [comment]
https://github.com/LUCIT-Systems-and-Development/unicorn-binance-websocket-api/releases/tag/1.46.2
