### ISSUE TITLE
Exception ConnectionClosed - error_msg: received 1001 (going away); then sent 1001 (going away)

### ISSUE THREAD

**Issue by AutoAuto** [LUCIT-Systems-and-Development/unicorn-binance-websocket-api#354]
### Version of this library.

1.46.1

### Solution to Issue cannot be found in the documentation or other Issues and also occurs in the latest version of this library.

- [X] I checked the documentation and other Issues. I am using the latest version of this library.

### Hardware?

Local server/workstation

### Operating System?

Linux

### Python version?

Python3.7

### Logging output

```shell
BinanceWebSocketApiSocket.start_socket(93123223cd12-e1b8-d367-2b2e-2b5b6c61, ['arr'], ['!ticker']) - Exception ConnectionClosed - error_msg: received 1001 (going away); then sent 1001 (going away)
BinanceWebSocketApiManager.stream_is_crashing(93123223cd12-e1b8-d367-2b2e-2b5b6c61)
```

### Processing method?

stream_buffer

### Used endpoint?

concerns all

### Issue

How to properly handle this error ? After this I dont have price updates. My manager init is here:

self.ubwa_com = BinanceWebSocketApiManager(exchange="binance.com", high_performance=True, disable_colorama=True)

**Comment by oliver-zehentleitner** [comment]
What do you mean with "handle". The stream should get restarted bei UBWA itself. Isnt it? Or do you mean how to handle the data gap or how the get programmatically informed of the disconnect?
