### ISSUE TITLE
websocket crashing....

### ISSUE THREAD

**Issue by behdad097** [LUCIT-Systems-and-Development/unicorn-binance-websocket-api#358]
### Version of this library.

1.46.1

### Solution to Issue cannot be found in the documentation or other Issues and also occurs in the latest version of this library.

- [X] I checked the documentation and other Issues. I am using the latest version of this library.

### Hardware?

VPS or other cloud hosting

### Operating System?

Linux

### Python version?

Python3.11

### Logging output

```shell
BinanceWebSocketApiManager.stream_is_crashing(0bf3d7383acd-5ace-c594-5283-d17d6e3a)
```

### Processing method?

stream_buffer

### Used endpoint?

binance.com

### Issue

Hello good evening
I have this issue on three servers and on each of them the websocket sometimes crashing and doesn't get the new closed candles.
I find it in log file , when I checked the time of candles that I don't have in my DB and check them by log file, I find out that when websocket crash , it doesn't get new closed candles

**Comment by oliver-zehentleitner** [comment]
Hey! 

I would need the full log or at minimum the logged reason for the crash.

And I recommend reading this:
https://github.com/LUCIT-Systems-and-Development/unicorn-binance-websocket-api/discussions/254
https://github.com/LUCIT-Systems-and-Development/unicorn-binance-websocket-api/discussions/255

**Comment by oliver-zehentleitner** [comment]
Feel free to reopen if needed.
