### ISSUE TITLE
Fails to install using pip or the setup.py 

### ISSUE THREAD

**Issue by nazguul512** [LUCIT-Systems-and-Development/unicorn-binance-websocket-api#368]
### Solution to Issue cannot be found in the documentation or other Issues and also occurs in the latest version of this library.

- [X] I checked the documentation and other Issues. I am using the latest version of this library.

### Version of this library.

lucit_licensing_python: not found
unicorn_fy: not found
unicorn_binance_local_depth_cache: not found
unicorn_binance_rest_api: not found
unicorn_binance_trailing_stop_loss: not found
unicorn_binance_websocket_api: not found

### Hardware?

Raspberry Pi

### Operating System?

Linux

### Python version?

Python3.10

### Installed wheel files

```shell
WARNING: Package(s) not found: unicorn-binance-rest-api
```

### Installed packages

```shell
Package              Version
-------------------- ------------
aniso8601            9.0.1
anyio                4.0.0
appdirs              1.4.4
APScheduler          3.6.3
beautifulsoup4       4.12.2
blinker              1.7.0
bs4                  0.0.2
cachetools           5.3.2
certifi              2023.7.22
cffi                 1.16.0
charset-normalizer   3.3.2
cheroot              10.0.0
click                8.1.7
colorama             0.4.6
cryptography         42.0.1
cssselect            1.2.0
Cython               3.0.8
decorator            5.1.1
et-xmlfile           1.1.0
exceptiongroup       1.1.3
fake-useragent       1.4.0
feedparser           6.0.11
Flask                3.0.2
Flask-RESTful        0.3.10
frozendict           2.3.8
google-auth          2.23.4
google-auth-oauthlib 1.1.0
gspread              5.12.0
h11                  0.14.0
html5lib             1.1
httpcore             1.0.2
httplib2             0.22.0
httpx                0.25.1
idna                 3.4
importlib-metadata   7.0.1
itsdangerous         2.1.2
jaraco.functools     4.0.0
Jinja2               3.1.3
lxml                 4.9.3
MarkupSafe           2.1.5
more-itertools       10.2.0
multitasking         0.0.11
numpy                1.26.2
oauth2client         4.1.3
oauthlib             3.2.2
openpyxl             3.1.2
pandas               2.1.3
parse                1.20.1
peewee               3.17.0
pip                  24.0
psutil               5.9.8
pyasn1               0.5.0
pyasn1-modules       0.3.0
pycparser            2.21
pyee                 8.2.2
pyparsing            3.1.1
pyppeteer            1.0.2
pyquery              2.0.0
PySocks              1.7.1
python-dateutil      2.8.2
python-telegram-bot  13.0
pytz                 2023.3.post1
requests             2.31.0
requests-html        0.10.0
requests-oauthlib    1.3.1
rsa                  4.9
setuptools           69.1.1
sgmllib3k            1.0.0
six                  1.16.0
sniffio              1.3.0
soupsieve            2.5
telegram-send        0.24
termcolor            2.3.0
tornado              6.4
tqdm                 4.66.2
tradingview-ta       3.3.0
tzdata               2023.3
tzlocal              5.2
ujson                5.9.0
urllib3              1.26.18
w3lib                2.1.2
webencodings         0.5.1
websocket-client     1.6.4
websockets           10.4
Werkzeug             3.0.1
wheel                0.42.0
yahoo-fin            0.8.9.1
yfinance             0.2.36
zipp                 3.17.0
```

### Processing method?

stream_buffer

### Used endpoint?

binance.us

### Issue

while trying to install this library and use it, i get this error on running pip install:
pip install unicorn-binance-websocket-api
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting unicorn-binance-websocket-api
  Using cached unicorn-binance-websocket-api-2.1.4.tar.gz (1.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      Traceback (most recent call last):
        File "/home/pi/.local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/pi/.local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/pi/.local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-cwvlhdg1/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-cwvlhdg1/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-cwvlhdg1/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 28, in <module>
        File "/tmp/pip-build-env-cwvlhdg1/overlay/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1010, in cythonize
          module_list, module_metadata = create_extension_list(
        File "/tmp/pip-build-env-cwvlhdg1/overlay/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 845, in create_extension_list
          for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
        File "/tmp/pip-build-env-cwvlhdg1/overlay/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 117, in nonempty
          raise ValueError(error_msg)
      ValueError: 'unicorn_binance_websocket_api/__init__.py' doesn't match any files
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

I have used this library in the past, one year ago and it worked flawlessly, no issue on install or anything.
Since then, I have upgraded the python version from its original provided in RapiOS to python3.10.
Now, I have to reinstall all pip packages to python3.10, even thou I have them installed already for the old version of python.
No other pip packages I needed throwed me this kind of error, I don't even understand it.

**Comment by oliver-zehentleitner** [comment]
Hello @nazguul512!

We offer the library since 2.0.0 as compiled C-Extention for Python. This is architecture specific and there is no suitable wheel for the Raspberry. 

May I ask you to come to the support chat. The chat is free, but we can work more dynamically on a solution for you: 
https://www.lucit.tech/get-support.html

Best regards,
Oliver

**Comment by oliver-zehentleitner** [comment]
Closed in chat.

**Comment by oliver-zehentleitner** [comment]
Hello!
The new update works now also on all raspberry models:
https://pypi.org/project/unicorn-binance-websocket-api/2.2.0/

The installation of the entire Unicorn Binance Suite can take up to an hour due to the compilation! Especially after "Building Wheels ..." not much happens on the screen for a long time, just be patient!

These are the dependencies of such a system, it is best to install everything once in advance:
https://github.com/LUCIT-Systems-and-Development/unicorn-binance-suite/wiki/Installation#for-apt-ubuntu-debian-on-raspberry-pi
