### ISSUE TITLE
Logo for this project

### ISSUE THREAD

**Issue by oliver-zehentleitner** [LUCIT-Systems-and-Development/unicorn-binance-websocket-api#55]
Hello!
Is there someone who would make a logo for this project?
Something with a unicorn, binance and a webstream?
Thank you!
Oliver

**Comment by gfox72** [comment]
![Schermafbeelding 2020-07-28 om 22 24 19](https://user-images.githubusercontent.com/14833717/88718181-db348680-d121-11ea-9957-042a1bcfe0e4.png)

**Comment by oliver-zehentleitner** [comment]
Thank you so much :+1: 

1. Could you also provide me one example with the text "UNICORN Binance Websocket API"?
2. If you fork this repository, upload the logo you made to your fork and then open a pull request, I would merge the fork and then you are automatically added to the contributors list! Would you like to do that?

**Comment by gfox72** [comment]
done, I did SVG which is vector and a few PNG's, if you have specific needs on resolutions let me know

**Comment by oliver-zehentleitner** [comment]
Thanks, where did you place them?

**Comment by oliver-zehentleitner** [comment]
Ah, I found them! Thanks!
https://github.com/gfox72/unicorn-binance-websocket-api/tree/223d24f1bfcf777959c60a3a731e81abddf44c42

**Comment by gfox72** [comment]
yeah, when I saw your question I noticed you actually created a folder for them (which I overlooked when I uploaded them), now moved them to that logo folder (I'm a real noob when it comes to using github so hope it works out). Let me know if you want any changes to them, they were intended as quick draft but actually came out quite well. Just keep in mind binance is a bigger entity which may not like you to use a modified version of their logo, not bad to ask for their consent.

**Comment by oliver-zehentleitner** [comment]
In the SVG version the text "API" is out of scope! I tried to fix that but it seems i dont have the right apps for that...

**Comment by oliver-zehentleitner** [comment]
I will get in contact with binance and ask them!

Your logo is online and you are added to contributors!

**Comment by gfox72** [comment]
> In the SVG version the text "API" is out of scope! I tried to fix that but it seems i dont have the right apps for that...

Do you mean it shows left out in the SVG (which would be strange as I have it showing with multiple viewers) or do you mean it should not be put there for SVG ('out of scope' as 'in was not asked') ? Let me know.

**Comment by gfox72** [comment]
screenshot with file preview on MAC (don't expect different behaviour on other OS or tools)
![Schermafbeelding 2020-07-29 om 14 15 34](https://user-images.githubusercontent.com/14833717/88798927-fa74f780-d1a5-11ea-8aa0-febc20434bcc.png)

**Comment by oliver-zehentleitner** [comment]
Ah, maybe its because you use a font in the SVG thats not available on my system.... SVGs can have included path or something like that... its very different to your mac screenshot:
![Screenshot_20200729_141725](https://user-images.githubusercontent.com/47597331/88799200-635c6f80-d1a6-11ea-971a-1ffea018856f.png)

**Comment by gfox72** [comment]
yep, I'll fix it

**Comment by gfox72** [comment]
done, with a pull request, let me know if anything else

**Comment by oliver-zehentleitner** [comment]
Thank you so much!

Just a hint! You have a fork that you can edit. If you are ready with the changes then there is an extra button "pull request", only then i will get a notification that you are ready and want me to merge the changes. Then its a pull request :)

Best regards!

**Comment by gfox72** [comment]
> Just a hint! You have a fork that you can edit. If you are ready with the changes then there is an extra button "pull request", only then i will get a notification that you are ready and want me to merge the changes. Then its a pull request :)

thanks, each time I get closer to these type of controls I'm in doubt if I'll mess things up lol, learning as we go

**Comment by oliver-zehentleitner** [comment]
you cant damage anything in the main repository!

... learning as we go ... :+1:

**Comment by oliver-zehentleitner** [comment]
I asked a binance angel via telegram and the answer is:
> Unfortunately, the word is that you could use our logo, but would have to avoid modifying it. In other words, the square would need to be untouched, maybe the unicorn incorporated in some other way alongside it.

> Seems like a strict requirement that the Binance logo itself not be modified. I do like your design, though. Not my decision.

> Again, this came from the top. There is nothing that can be done. It is a strict decision for others not to modify the logo. I don't agree with the decision, personally, but talking to someone else is not going to change it.

What should we do? Redesign or try it with a tweet to cz_binance?

**Comment by gfox72** [comment]
best to redesign, I'll drop a few suggestions soon

**Comment by oliver-zehentleitner** [comment]
ping :D

**Comment by gfox72** [comment]
Hi Oliver,

Have been focussing on some other things but got so far back end July, didn’t like these as much as the original though

**Comment by oliver-zehentleitner** [comment]
No problem, just wanted to remind you. 

It hurts  me too, I really like the first logo!

Lieve groeten

**Comment by oliver-zehentleitner** [comment]
:)

**Comment by oliver-zehentleitner** [comment]
@gfox72 any news? it must be perfect, just not illegal :)

**Comment by oliver-zehentleitner** [comment]
I removed the current logo. 

Is there anyone who could create a new logo?

**Comment by bashman** [comment]
Hi. Is open the logo contest design?

**Comment by oliver-zehentleitner** [comment]
It isnt really a contest, nothing to win and no competitors :D

But yes, I would be happy about a nice logo for this project!

**Comment by bashman** [comment]
Proposal 1. 

![unicorn](https://user-images.githubusercontent.com/1690516/99116246-af9ab680-25c1-11eb-851e-836b11f8561b.png)

I decided to place the unicorn on the logo of the websocket technology. The fact is that the binance logo is very evident and could involve copyright or trademark issues, this happens a lot. I put red and green marks, which remind the ohlc graphics of the market. I put the binance logo in the form of an eye, so this is under discussion.

**Comment by oliver-zehentleitner** [comment]
Thanks so much!

Could you just add the text "UNICORN Binance Websocket API"

Its just an idea, but maybe you could do something with it:
Funny would be a river streaming down the binance mountain and a unicorn is surfing it down. In it are swimming (like fishes) symbols for datatypes/channeltypes (trades, kline, orderbook) and currencies like btc, eth,... and dont forget the rainbow :D

**Comment by oliver-zehentleitner** [comment]
... and maybe a python snake

**Comment by bashman** [comment]
> Thanks so much!
> 
> Could you just add the text "UNICORN Binance Websocket API"
> 
> Its just an idea, but maybe you could do something with it:
> Funny would be a river streaming down the binance mountain and a unicorn is surfing it down. In it are swimming (like fishes) symbols for datatypes/channeltypes (trades, kline, orderbook) and currencies like btc, eth,... and dont forget the rainbow :D

Yes!. In the next days...

**Comment by oliver-zehentleitner** [comment]
@bashman  maybe you want to join https://t.me/unicorndevs

(everyone else is welcome too)

**Comment by oliver-zehentleitner** [comment]
hi @bashman ... :)
