### ISSUE TITLE
Add total used memory of the process to monitoring output

### ISSUE THREAD

**Issue by oliver-zehentleitner** [LUCIT-Systems-and-Development/unicorn-binance-websocket-api#68]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Add total used RAM of the process to the monitoring output in the rest sever module.
https://stackoverflow.com/questions/938733/total-memory-used-by-python-process

https://github.com/oliver-zehentleitner/unicorn-binance-websocket-api/blob/536644fbe35da4d66041c4eefb6dfa9b5b6254a0/unicorn_binance_websocket_api/unicorn_binance_websocket_api_manager.py#L1272
https://github.com/oliver-zehentleitner/unicorn-binance-websocket-api/blob/536644fbe35da4d66041c4eefb6dfa9b5b6254a0/unicorn_binance_websocket_api/unicorn_binance_websocket_api_manager.py#L1319

**Describe alternatives you've considered**

**Additional context**

**Comment by oliver-zehentleitner** [comment]
Add also a streams label.

**Comment by oliver-zehentleitner** [comment]
There are a couple of fields that could be added to monitoring export.

**Comment by DrPaprikaa** [comment]
Hi, any updates on this ? Do you have info about how the memory usage behaves after hours/days of non-stop running ?

**Comment by oliver-zehentleitner** [comment]
I added auto_data_clean_up feature...
